name: LagScope
main: me.priyme.lagscope.LagScopePlugin
version: 1.0.0
api-version: '1.21'
author: PrIyme
folia-supported: false
commands:
  lag:
    description: LagScope main command
    usage: /lag
    aliases: [lagscope]
permissions:
  lagscope.use:
    default: true
  lagscope.admin:
    default: op
  lagscope.tp:
    default: op
